language: python
env: TRAVIS_TEST=1
python:
  - "3.7"

install:
    - pip3 install coverage
    - pip3 install pytest
    - pip3 install pytest-cov
    - python setup.py install

script:
  - pytest --cov=contemply -v